version: 0.2

phases:
  install:
    runtime-versions:
      php: 8.1
    commands:
      - echo Installing dependencies...
      - if [ -f composer.json ]; then composer install --no-dev; fi

  build:
    commands:
      - echo Build started on `date`
      - echo Nothing to compile for PHP app

artifacts:
  files:
    - '**/*'
